name: Deploy client
run-name: Deploy client

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Build
        run: |
          echo "VITE_SERVER_URL=https://rubicon-websockets.ajmuht.eu" >> .env
          npm install
          npm run client-build

      - name: Deploy
        uses: medvesek/infrastructure/github-actions/lkwdeploy@master
        with:
          cloudflare-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          server-ip: ${{ secrets.AQUILA_IP }}
          ssh-user: ${{ secrets.SSH_USER }}
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE_GITHUB_ACTIONS }}
          config: lkw-client.yaml
